### ISSUE TITLE
Same key reported on multiple lines with varying size

### ISSUE THREAD

**Issue by boxluecke** [box/memsniff#4]
Noticed this was happening for a memcache key that was changing size during memsniff operation, so it was being aggregated on several lines with their own size and bandwidth numbers.

Suggested fixes include:
A) Using max size seen (overestimates size/bandwidth)
B) Using min size seen (underestimates size/bandwidth)
C) Using avg size seen (more accurate, but may have perf impact / other)
D) Regardless of above, add UI indication that size is fluctuating / not constant for a key; could prepend/append a ~, *, other

**Comment by BoxMiles** [comment]
Fixed by default configuration of flexible aggregation to take the max(size).
